name: CI - Test, Lint & Build

on: 
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '*.md'

jobs:
  test-and-build:
    name: Test, Lint & Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Cache database package build
        uses: actions/cache@v4
        with:
          path: |
            packages/database/dist
            packages/database/node_modules/.cache
          key: database-build-${{ hashFiles('packages/database/package.json', 'packages/database/src/**/*') }}
          restore-keys: |
            database-build-

      - name: Install dependencies
        run: npm ci

      - name: Build shared database package
        run: |
          cd packages/database
          npm run build

      - name: Generate Prisma client
        run: npm run db:generate

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Build applications (test build)
        run: npm run build
