# .github/workflows/test-ssh.yml
name: Test SSH Connection
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_PRIVATE_KEY }}
          port: ${{ secrets.DO_PORT }}
          script: |
            echo "SSH connection successful!"
            whoami
            pwd
            ls -la
